// =============================================================================
// =============================================================================
// 09v: Independent-validation NAVIGATOR APP
// =============================================================================
// =============================================================================
//
// A GEE App (ui.*) that replaces the per-validator inspector workflow. Publish it
// once under the OWNER account (Apps > New App): it then runs under the owner's
// credentials, so the three validators need NO Earth Engine account and NO shared
// assets — they just open the App URL.
//
// It is a PURE NAVIGATOR + VIEWER. It does not (and cannot) persist anything:
// GEE Apps never write to Drive/Sheets. Responses are typed by each validator into
// their OWN Google Sheet (blind, one per person) in parallel with this app.
//
// Workflow (per validator):
//   1. Pick your name (top-left). The app loads YOUR assigned pxid list.
//   2. Walk the list with ◀ / ▶ (or type a pxid to resume where your Sheet left
//      off). Toggle year 2017 / 2025 to inspect each season.
//   3. Read the current pxid shown; fill that row in your Google Sheet:
//      class_2017, class_2017_confidence, class_2025, class_2025_confidence.
//
// REFERENCE PRIORITY: high-resolution imagery in Google Earth Pro (visible yellow
// bloom, open the matching <pxid>.kml) is the PRIMARY evidence. The mosaics and the
// Sentinel-2 NDYI series here are phenological SUPPORT only — they reuse the model's
// own features, so don't let them be the sole criterion (avoid circularity).
// =============================================================================


// =============================================================================
// 0. CONFIG
// =============================================================================
var ASSET_PREFIX = 'projects/ee-licanemartinez/assets/Retamap/';
var FC_ASSET     = ASSET_PREFIX + '09v_valPoints_fc';        // blind FC, pxid only

// Per-validator ordered pxid lists (auto-generated by 09v_valRandomize.R).
// Matches each validator's Google-Sheet row order → app prev/next == sheet rows.
var ASSIGN = require('users/licanemartinez/Retamap:09v_valAssign.js').ASSIGN;

var VALIDATORS = ['lican', 'sofi', 'jaime'];
var VAL_YEARS  = ['2017', '2025'];

// Fill these in AFTER creating the three Google Sheets (one per validator).
// Leave '' and the app just shows a hint instead of a working link.
var SHEET_URLS = {
  lican: 'https://docs.google.com/spreadsheets/d/1wm9Ie9bp0FGXwN54wPTyRSGPYqUC2tMmiZD78msWzBA/edit?usp=sharing',
  sofi:  'https://docs.google.com/spreadsheets/d/1kVk5R2ZJfVYEGUx9JLCX_FG7v_PaGhSQtY6rCxBCigA/edit?usp=sharing',
  jaime: 'https://docs.google.com/spreadsheets/d/1fD79Y1mDHW8kDuvrp4l4aAz2BkfmeYy0q1I0nl6bM9Q/edit?usp=sharing'
};

// Shared visualization params (identical to 09v_valInspector_TEMPLATE.js).
// var NDYI_VIS = {min: 0, max: 0.2, palette: ['ffffff', 'ffff66', 'ff9900', 'cc3300']};
// var NDYI_VIS = {min: 0, max: 0.2, palette: ['000000', '990000', 'ff9900', 'ffff66']};
var NDYI_VIS = {min: 0, max: 0.2, palette: ['000000', '990000', 'ff9900', 'ffff66']};
var visTC = {
  bands: ['B4', 'B3', 'B2'],
  min: [300, 300, 500],   // higher 3rd value tames the blue haze / shadows
  max: 1400,              // lower = more overall saturation
  gamma: 0.6
};
var visTC_feb = Object.assign({}, visTC, {bands: ['B4_feb', 'B3_feb', 'B2_feb']});

var fc = ee.FeatureCollection(FC_ASSET);


// =============================================================================
// 1. CLIENT-SIDE STATE
// =============================================================================
// span  = plotted window in years (1 = just the target season; N adds N-1 extra
//         years on each side). clicked = optional user-clicked comparison point.
var state = {validator: null, list: [], idx: 0, year: 2017, span: 1,
             aoi: null, centro: null, clicked: null};
var clickedLayer = null;   // ref to the clicked-point map layer (for removal)


// =============================================================================
// 2. WIDGETS
// =============================================================================
var title = ui.Label('Validación de retama — 09v', {
  fontWeight: 'bold', fontSize: '18px', margin: '4px 8px'
});

var validatorSelect = ui.Select({
  items: VALIDATORS,
  placeholder: 'Elegí tu nombre…',
  onChange: setValidator,
  style: {stretch: 'horizontal'}
});

var sheetLink = ui.Label('(elegí tu nombre para ver tu planilla)', {margin: '2px 8px'});

var pxidBigLabel = ui.Label('—', {
  fontWeight: 'bold', fontSize: '26px', color: '#b30000', margin: '6px 8px 0 8px'
});
var progressLabel = ui.Label('punto — de —', {fontSize: '12px', margin: '0 8px 6px 8px'});

var prevBtn = ui.Button({label: '◀ Anterior', onClick: function() { step(-1); },
                         style: {stretch: 'horizontal'}});
var nextBtn = ui.Button({label: 'Siguiente ▶', onClick: function() { step(1); },
                         style: {stretch: 'horizontal'}});
var navRow = ui.Panel([prevBtn, nextBtn], ui.Panel.Layout.flow('horizontal'),
                      {stretch: 'horizontal'});

var pxidBox = ui.Textbox({
  placeholder: 'ir a pxid (ej. px001)…',
  onChange: jumpToPxid,
  style: {stretch: 'horizontal'}
});

var yearSelect = ui.Select({
  items: VAL_YEARS, value: '2017', onChange: setYear,
  style: {stretch: 'horizontal'}
});

// Plotted year-window (± años). Default '1' = only the target flowering season.
var spanBox = ui.Textbox({
  value: '1', onChange: setSpan,
  style: {stretch: 'horizontal'}
});

var clearClickBtn = ui.Button({
  label: '✖ Limpiar punto clickeado', onClick: clearClicked,
  style: {stretch: 'horizontal'}
});

var statusLabel = ui.Label('', {color: 'gray', fontSize: '12px', margin: '2px 8px'});

var help = ui.Label(
  'Evidencia PRIMARIA: alta resolución en Google Earth Pro (bloom amarillo Nov–Dic ' +
  '= retama; abrí el <pxid>.kml). Los mosaicos y la serie NDYI (Sentinel-2) de acá son apoyo ' +
  'fenológico. Podés CLICKEAR el mapa para agregar la serie NDYI de otro punto ' +
  '(comparación). Cargá en tu planilla: class_2017/2025 (Retama/No_retama) y su ' +
  'confianza 0–10 (0 = no se sabe).',
  {fontSize: '11px', color: '#444', margin: '8px 8px'}
);

var controlPanel = ui.Panel({
  widgets: [
    title, validatorSelect, sheetLink,
    ui.Label('─────────────', {margin: '4px 8px', color: '#ccc'}),
    pxidBigLabel, progressLabel, navRow,
    ui.Label('Retomar / saltar:', {fontSize: '12px', margin: '6px 8px 0 8px'}), pxidBox,
    ui.Label('Año:', {fontSize: '12px', margin: '6px 8px 0 8px'}), yearSelect,
    ui.Label('Años a graficar (± ventana):', {fontSize: '12px', margin: '6px 8px 0 8px'}), spanBox,
    clearClickBtn,
    statusLabel, help
  ],
  style: {width: '300px', padding: '4px'}
});

var chartPanel = ui.Panel({style: {width: '360px', padding: '4px'}});

var map = ui.Map();
map.setOptions('SATELLITE');
map.setCenter(-71.5, -41.5, 8);   // Patagonia norte, before a point is chosen
map.style().set('stretch', 'both');

// Click anywhere → set a comparison point and add its NDYI series to the panel.
map.onClick(function(coords) {
  if (!state.validator) { statusLabel.setValue('Elegí tu nombre primero.'); return; }
  state.clicked = ee.Geometry.Point([coords.lon, coords.lat]);
  addClickedMarker();
  refreshCharts();
});


// =============================================================================
// 3. NDYI TIME-SERIES CHARTS  (Aug (YEAR-span+1) → Mar (YEAR+span), region mean)
// =============================================================================
// span=1 → just the target season (Aug YEAR → Mar YEAR+1). span=N adds N-1 extra
// years on each side. region can be the validated 1 km AOI or a clicked point.
function spanWindow(year, span) {
  return {
    START: ee.Date.fromYMD(year - (span - 1), 8, 1),
    END:   ee.Date.fromYMD(year + span, 3, 31),
    y0:    year - (span - 1),
    y1:    year + span
  };
}

// ── 3a. Sentinel-2 (S2_HARMONIZED → no 2022 offset jump) + Cloud Score+ ──────
function buildS2Chart(region, year, span, label, colors) {
  var w = spanWindow(year, span);

  // Snap the per-acquisition NDYI onto the 4326 mosaic grid — the grid the map
  // classified on (01_MergedBands, exported scale:10 no crs). A Point sample then
  // resolves the exact prediction pixel (native S2 is UTM19S → offset ~½ px).
  var proj = ee.Image(ASSET_PREFIX + '01_MergedBands_' + year).select('B4').projection();

  var csPlus = ee.ImageCollection('GOOGLE/CLOUD_SCORE_PLUS/V1/S2_HARMONIZED');
  var s2 = ee.ImageCollection('COPERNICUS/S2_HARMONIZED')
    .filterBounds(region)
    .filterDate(w.START, w.END)
    .map(function(img) { return img.linkCollection(csPlus, ['cs']); })
    .map(function(img) { return img.updateMask(img.select('cs').gte(0.6)); })
    .map(function(img) {
      return img.normalizedDifference(['B3', 'B2']).rename('NDYI')
        .reproject(proj)                                  // → prediction grid
        .copyProperties(img, ['system:time_start']);
    });

  return ui.Chart.image.series({
    imageCollection: s2.select('NDYI'),
    region: region, reducer: ee.Reducer.mean(), scale: 10,
    xProperty: 'system:time_start'
  }).setOptions({
    title: 'Sentinel-2 NDYI  Ago ' + w.y0 + '–Mar ' + w.y1 + '  (' + label + ')',
    hAxis: {title: 'fecha'},
    vAxis: {title: 'NDYI (media región)', viewWindow: {min: -0.3, max: 0.5}},
    pointSize: 4, lineWidth: 1, colors: colors || ['1f78b4']
  });
}

// ── 3b. HLS (Landsat + Sentinel harmonised); NDYI is a ratio → no scaling ─────
function buildHlsChart(region, year, span, label, colors) {
  var w = spanWindow(year, span);

  // Same prediction-grid snap as the S2 chart (HLS is 30 m native → upsampled).
  var proj = ee.Image(ASSET_PREFIX + '01_MergedBands_' + year).select('B4').projection();

  var hlsMask = function(img) {
    var f = img.select('Fmask');
    var clear = f.bitwiseAnd(1 << 1).eq(0).and(f.bitwiseAnd(1 << 3).eq(0));
    return img.updateMask(clear);
  };
  var hlsNDYI = function(img) {
    return hlsMask(img).normalizedDifference(['B3', 'B2']).rename('NDYI')
      .reproject(proj)                                    // → prediction grid
      .copyProperties(img, ['system:time_start']);
  };
  var hlsL = ee.ImageCollection('NASA/HLS/HLSL30/v002')
    .filterBounds(region).filterDate(w.START, w.END).select(['B2', 'B3', 'Fmask']).map(hlsNDYI);
  var hlsS = ee.ImageCollection('NASA/HLS/HLSS30/v002')
    .filterBounds(region).filterDate(w.START, w.END).select(['B2', 'B3', 'Fmask']).map(hlsNDYI);
  var hls = hlsL.merge(hlsS).sort('system:time_start');

  return ui.Chart.image.series({
    imageCollection: hls.select('NDYI'),
    region: region, reducer: ee.Reducer.mean(), scale: 30,
    xProperty: 'system:time_start'
  }).setOptions({
    title: 'HLS NDYI  Ago ' + w.y0 + '–Mar ' + w.y1 + '  (' + label + ')',
    hAxis: {title: 'fecha'}, vAxis: {title: 'NDYI (media región)'},
    pointSize: 4, lineWidth: 1, colors: colors || ['1b7837']
  });
}

// ── 3c. (Re)build the chart panel: validated pixel + optional clicked point ──
function refreshCharts() {
  if (!state.validator || !state.centro) return;
  var pxid = state.list[state.idx];
  var year = state.year, span = state.span;

  chartPanel.clear();
  chartPanel.add(ui.Label('Serie NDYI (apoyo fenológico)',
                          {fontWeight: 'bold', fontSize: '13px', margin: '4px 8px'}));

  // Validated pixel — reduced over the target pixel (centroid), NOT the 1 km AOI,
  // so it matches clicking that same pixel (AOI mean would dilute the bloom to ~0).
  chartPanel.add(ui.Label('▍Píxel validado: ' + pxid,
                          {fontSize: '12px', color: '#1f78b4', margin: '4px 8px 0 8px'}));
  chartPanel.add(buildS2Chart(state.centro, year, span, pxid, ['1f78b4']));
  // HLS del píxel validado (descomentar para prenderla — S2 y HLS pueden convivir):
  // chartPanel.add(buildHlsChart(state.centro, year, span, pxid, ['1b7837']));

  // Optional clicked comparison point — magenta.
  if (state.clicked) {
    chartPanel.add(ui.Label('▍Punto clickeado (comparación)',
                            {fontSize: '12px', color: '#e31a1c', margin: '10px 8px 0 8px'}));
    chartPanel.add(buildS2Chart(state.clicked, year, span, 'click', ['e31a1c']));
    // HLS del punto clickeado (descomentar si prendés la de arriba):
    // chartPanel.add(buildHlsChart(state.clicked, year, span, 'click', ['b15928']));
  }
}


// =============================================================================
// 4. RENDER  (recenter=true on pxid change, false on year toggle)
// =============================================================================
function render(recenter) {
  if (!state.validator) return;
  var pxid = state.list[state.idx];
  var year = state.year;

  pxidBigLabel.setValue(pxid);
  progressLabel.setValue('punto ' + (state.idx + 1) + ' de ' + state.list.length +
                         ' · ' + pxid);
  pxidBox.setValue(pxid, false);   // reflect current pxid, do NOT fire onChange
  statusLabel.setValue('');

  // Point + 1 km neighbourhood (blind: contour only, no map label) --------------
  var feat    = ee.Feature(fc.filter(ee.Filter.eq('pxid', pxid)).first());
  var contour = feat.geometry();
  var centro  = contour.centroid(1);
  var aoi     = centro.buffer(500).bounds();
  state.aoi    = aoi;      // 1 km box: map extent / clip only

  // Four mosaic layers from 01_MergedBands_<year> ------------------------------
  var merged = ee.Image(ASSET_PREFIX + '01_MergedBands_' + year).clip(aoi);
  var proj10 = merged.select('B4').projection();   // 4326 prediction grid (the pixel the map classified)

  // The FC centroid is a UTM19S pixel center (points sampled on EPSG:32719), which
  // lands inside — but not centered in — the 4326 prediction pixel. Snap it to the
  // center of that 4326 pixel so the dot, the red box, and the validated chart all
  // resolve to the same prediction pixel.
  var pc = ee.Image.pixelLonLat().reproject(proj10)
    .reduceRegion({reducer: ee.Reducer.first(), geometry: centro, scale: 10});
  centro = ee.Geometry.Point([pc.get('longitude'), pc.get('latitude')]);
  state.centro = centro;   // 4326 prediction pixel center: region for the validated NDYI chart

  // Target pixel highlighted as a RASTER on the 4326 prediction grid — the same
  // grid the (snapped) centro, the dot, and the validated chart resolve to, so
  // all three coincide with the pixel the map classified. Blind: derived from
  // centro + raw imagery only, never from m2017/m2025 or predictions.
  var pixHi = ee.Image(0).byte()
    .paint(ee.FeatureCollection([ee.Feature(centro)]), 1)   // pixel under centro = 1
    .selfMask()
    .reproject(proj10);                                     // snap to prediction grid

  map.layers().reset();
  map.addLayer(aoi, {color: 'ffffff'}, '1km AOI', false);
  map.addLayer(merged, visTC, year + ' TrueColor NovDec', true);
  map.addLayer(merged.select('NDYI'), NDYI_VIS, year + ' NDYI NovDec', false);
  map.addLayer(merged, visTC_feb, year + ' TrueColor Feb', false);
  map.addLayer(merged.select('NDYI_feb'), NDYI_VIS, year + ' NDYI Feb', false);
  map.addLayer(pixHi, {palette: ['FF0000']}, 'pixel ' + pxid, true, 0.4);
  map.addLayer(centro, {color: '00FFFF'}, 'centroid', true);

  // layers().reset() above dropped any clicked marker → re-add it if still set.
  clickedLayer = null;
  addClickedMarker();

  if (recenter) map.centerObject(contour, 18);

  refreshCharts();
}

// Draw (or redraw) the user-clicked comparison point as a magenta marker.
function addClickedMarker() {
  if (!state.clicked) return;
  if (clickedLayer) map.remove(clickedLayer);
  clickedLayer = map.addLayer(state.clicked, {color: 'FF00FF'}, 'punto clickeado', true);
}


// =============================================================================
// 5. CONTROL CALLBACKS
// =============================================================================
function setValidator(name) {
  state.validator = name;
  state.list = ASSIGN[name] || [];
  state.idx = 0;
  var url = SHEET_URLS[name];
  if (url) { sheetLink.setUrl(url); sheetLink.setValue('▶ Abrí tu planilla (' + name + ')'); }
  else     { sheetLink.setUrl('');  sheetLink.setValue('(configurá SHEET_URLS para ' + name + ')'); }
  render(true);
}

function setYear(y) {
  state.year = parseInt(y, 10);
  render(false);   // keep the map view fixed when comparing years
}

function setSpan(txt) {
  var n = parseInt(txt, 10);
  if (isNaN(n) || n < 1) {
    statusLabel.setValue('⚠ Años a graficar: entero ≥ 1 (default 1).');
    spanBox.setValue(String(state.span), false);
    return;
  }
  state.span = n;
  statusLabel.setValue('');
  refreshCharts();   // only the charts depend on the window; no map re-render
}

function clearClicked() {
  if (clickedLayer) { map.remove(clickedLayer); clickedLayer = null; }
  state.clicked = null;
  refreshCharts();
}

function step(d) {
  if (!state.validator) { statusLabel.setValue('Elegí tu nombre primero.'); return; }
  var n = state.list.length;
  state.idx = Math.max(0, Math.min(n - 1, state.idx + d));
  render(true);
}

function jumpToPxid(txt) {
  if (!state.validator) { statusLabel.setValue('Elegí tu nombre primero.'); return; }
  var t = (txt || '').trim();
  if (t === state.list[state.idx]) return;   // programmatic echo, ignore
  var i = state.list.indexOf(t);
  if (i < 0) { statusLabel.setValue('⚠ ' + t + ' no está en tu lista asignada.'); return; }
  state.idx = i;
  render(true);
}


// =============================================================================
// 6. LAYOUT
// =============================================================================
ui.root.clear();
ui.root.add(controlPanel);
ui.root.add(map);
ui.root.add(chartPanel);
