// =============================================================================
// =============================================================================
// 09v: Independent-validation NAVIGATOR APP
// =============================================================================
// =============================================================================
//
// A GEE App (ui.*) that replaces the per-validator inspector workflow. Publish it
// once under the OWNER account (Apps > New App): it then runs under the owner's
// credentials, so the three validators need NO Earth Engine account and NO shared
// assets — they just open the App URL.
//
// It is a PURE NAVIGATOR + VIEWER. It does not (and cannot) persist anything:
// GEE Apps never write to Drive/Sheets. Responses are typed by each validator into
// their OWN Google Sheet (blind, one per person) in parallel with this app.
//
// Workflow (per validator):
//   1. Pick your name (top-left). The app loads YOUR assigned pxid list.
//   2. Walk the list with ◀ / ▶ (or type a pxid to resume where your Sheet left
//      off). Toggle year 2017 / 2025 to inspect each season.
//   3. Read the current pxid shown; fill that row in your Google Sheet:
//      class_2017, class_2017_confidence, class_2025, class_2025_confidence.
//
// REFERENCE PRIORITY: high-resolution imagery in Google Earth Pro (visible yellow
// bloom, open the matching <pxid>.kml) is the PRIMARY evidence. The mosaics and the
// HLS NDYI series here are phenological SUPPORT only — they reuse the model's own
// features, so don't let them be the sole criterion (avoid circularity).
// =============================================================================


// =============================================================================
// 0. CONFIG
// =============================================================================
var ASSET_PREFIX = 'projects/ee-licanemartinez/assets/Retamap/';
var FC_ASSET     = ASSET_PREFIX + '09v_valPoints_fc';        // blind FC, pxid only

// Per-validator ordered pxid lists (auto-generated by 09v_valRandomize.R).
// Matches each validator's Google-Sheet row order → app prev/next == sheet rows.
var ASSIGN = require('users/licanemartinez/Retamap:09v_valAssign').ASSIGN;

var VALIDATORS = ['lican', 'sofi', 'jaime'];
var VAL_YEARS  = ['2017', '2025'];

// Fill these in AFTER creating the three Google Sheets (one per validator).
// Leave '' and the app just shows a hint instead of a working link.
var SHEET_URLS = {
  lican: '',
  sofi:  '',
  jaime: ''
};

// Shared visualization params (identical to 09v_valInspector_TEMPLATE.js).
var NDYI_VIS = {min: 0, max: 0.4, palette: ['ffffff', 'ffff66', 'ff9900', 'cc3300']};
var visTC = {
  bands: ['B4', 'B3', 'B2'],
  min: [300, 300, 500],   // higher 3rd value tames the blue haze / shadows
  max: 1400,              // lower = more overall saturation
  gamma: 0.6
};
var visTC_feb = Object.assign({}, visTC, {bands: ['B4_feb', 'B3_feb', 'B2_feb']});

var fc = ee.FeatureCollection(FC_ASSET);


// =============================================================================
// 1. CLIENT-SIDE STATE
// =============================================================================
var state = {validator: null, list: [], idx: 0, year: 2017};


// =============================================================================
// 2. WIDGETS
// =============================================================================
var title = ui.Label('Validación de retama — 09v', {
  fontWeight: 'bold', fontSize: '18px', margin: '4px 8px'
});

var validatorSelect = ui.Select({
  items: VALIDATORS,
  placeholder: 'Elegí tu nombre…',
  onChange: setValidator,
  style: {stretch: 'horizontal'}
});

var sheetLink = ui.Label('(elegí tu nombre para ver tu planilla)', {margin: '2px 8px'});

var pxidBigLabel = ui.Label('—', {
  fontWeight: 'bold', fontSize: '26px', color: '#b30000', margin: '6px 8px 0 8px'
});
var progressLabel = ui.Label('punto — de —', {fontSize: '12px', margin: '0 8px 6px 8px'});

var prevBtn = ui.Button({label: '◀ Anterior', onClick: function() { step(-1); },
                         style: {stretch: 'horizontal'}});
var nextBtn = ui.Button({label: 'Siguiente ▶', onClick: function() { step(1); },
                         style: {stretch: 'horizontal'}});
var navRow = ui.Panel([prevBtn, nextBtn], ui.Panel.Layout.flow('horizontal'),
                      {stretch: 'horizontal'});

var pxidBox = ui.Textbox({
  placeholder: 'ir a pxid (ej. px001)…',
  onChange: jumpToPxid,
  style: {stretch: 'horizontal'}
});

var yearSelect = ui.Select({
  items: VAL_YEARS, value: '2017', onChange: setYear,
  style: {stretch: 'horizontal'}
});

var statusLabel = ui.Label('', {color: 'gray', fontSize: '12px', margin: '2px 8px'});

var help = ui.Label(
  'Evidencia PRIMARIA: alta resolución en Google Earth Pro (bloom amarillo Nov–Dic ' +
  '= retama; abrí el <pxid>.kml). Los mosaicos y la serie HLS de acá son apoyo ' +
  'fenológico. Cargá en tu planilla: class_2017/2025 (Retama/No_retama) y su ' +
  'confianza 0–10 (0 = no se sabe).',
  {fontSize: '11px', color: '#444', margin: '8px 8px'}
);

var controlPanel = ui.Panel({
  widgets: [
    title, validatorSelect, sheetLink,
    ui.Label('─────────────', {margin: '4px 8px', color: '#ccc'}),
    pxidBigLabel, progressLabel, navRow,
    ui.Label('Retomar / saltar:', {fontSize: '12px', margin: '6px 8px 0 8px'}), pxidBox,
    ui.Label('Año:', {fontSize: '12px', margin: '6px 8px 0 8px'}), yearSelect,
    statusLabel, help
  ],
  style: {width: '300px', padding: '4px'}
});

var chartPanel = ui.Panel({style: {width: '360px', padding: '4px'}});

var map = ui.Map();
map.setOptions('SATELLITE');
map.setCenter(-71.5, -41.5, 8);   // Patagonia norte, before a point is chosen
map.style().set('stretch', 'both');


// =============================================================================
// 3. HLS NDYI TIME-SERIES CHART  (Aug YEAR → Mar YEAR+1, AOI mean)
// =============================================================================
function buildHlsChart(aoi, year, pxid) {
  var START = ee.Date.fromYMD(year, 8, 1);
  var END   = ee.Date.fromYMD(year + 1, 3, 31);

  var hlsMask = function(img) {
    var f = img.select('Fmask');
    var clear = f.bitwiseAnd(1 << 1).eq(0).and(f.bitwiseAnd(1 << 3).eq(0));
    return img.updateMask(clear);
  };
  var hlsNDYI = function(img) {
    return hlsMask(img).normalizedDifference(['B3', 'B2']).rename('NDYI')
      .copyProperties(img, ['system:time_start']);
  };
  var hlsL = ee.ImageCollection('NASA/HLS/HLSL30/v002')
    .filterBounds(aoi).filterDate(START, END).select(['B2', 'B3', 'Fmask']).map(hlsNDYI);
  var hlsS = ee.ImageCollection('NASA/HLS/HLSS30/v002')
    .filterBounds(aoi).filterDate(START, END).select(['B2', 'B3', 'Fmask']).map(hlsNDYI);
  var hls = hlsL.merge(hlsS).sort('system:time_start');

  return ui.Chart.image.series({
    imageCollection: hls.select('NDYI'),
    region: aoi, reducer: ee.Reducer.mean(), scale: 30,
    xProperty: 'system:time_start'
  }).setOptions({
    title: 'HLS NDYI  Ago ' + year + '–Mar ' + (year + 1) + '  (' + pxid + ')',
    hAxis: {title: 'fecha'}, vAxis: {title: 'NDYI (media AOI)'},
    pointSize: 4, lineWidth: 1, colors: ['1b7837']
  });
}


// =============================================================================
// 4. RENDER  (recenter=true on pxid change, false on year toggle)
// =============================================================================
function render(recenter) {
  if (!state.validator) return;
  var pxid = state.list[state.idx];
  var year = state.year;

  pxidBigLabel.setValue(pxid);
  progressLabel.setValue('punto ' + (state.idx + 1) + ' de ' + state.list.length +
                         ' · ' + pxid);
  pxidBox.setValue(pxid, false);   // reflect current pxid, do NOT fire onChange
  statusLabel.setValue('');

  // Point + 1 km neighbourhood (blind: contour only, no map label) --------------
  var feat    = ee.Feature(fc.filter(ee.Filter.eq('pxid', pxid)).first());
  var contour = feat.geometry();
  var centro  = contour.centroid(1);
  var aoi     = centro.buffer(500).bounds();

  // Four mosaic layers from 01_MergedBands_<year> ------------------------------
  var merged = ee.Image(ASSET_PREFIX + '01_MergedBands_' + year).clip(aoi);
  map.layers().reset();
  map.addLayer(aoi, {color: 'ffffff'}, '1km AOI', false);
  map.addLayer(merged, visTC, year + ' TrueColor NovDec', true);
  map.addLayer(merged.select('NDYI'), NDYI_VIS, year + ' NDYI NovDec', false);
  map.addLayer(merged, visTC_feb, year + ' TrueColor Feb', false);
  map.addLayer(merged.select('NDYI_feb'), NDYI_VIS, year + ' NDYI Feb', false);
  map.addLayer(contour, {color: 'FF0000', fillColor: '00000000'}, 'pixel ' + pxid, true);
  map.addLayer(centro, {color: '00FFFF'}, 'centroid', true);
  if (recenter) map.centerObject(contour, 18);

  // HLS NDYI series ------------------------------------------------------------
  chartPanel.clear();
  chartPanel.add(ui.Label('Serie NDYI (apoyo fenológico)',
                          {fontWeight: 'bold', fontSize: '13px', margin: '4px 8px'}));
  chartPanel.add(buildHlsChart(aoi, year, pxid));
}


// =============================================================================
// 5. CONTROL CALLBACKS
// =============================================================================
function setValidator(name) {
  state.validator = name;
  state.list = ASSIGN[name] || [];
  state.idx = 0;
  var url = SHEET_URLS[name];
  if (url) { sheetLink.setUrl(url); sheetLink.setValue('▶ Abrí tu planilla (' + name + ')'); }
  else     { sheetLink.setUrl('');  sheetLink.setValue('(configurá SHEET_URLS para ' + name + ')'); }
  render(true);
}

function setYear(y) {
  state.year = parseInt(y, 10);
  render(false);   // keep the map view fixed when comparing years
}

function step(d) {
  if (!state.validator) { statusLabel.setValue('Elegí tu nombre primero.'); return; }
  var n = state.list.length;
  state.idx = Math.max(0, Math.min(n - 1, state.idx + d));
  render(true);
}

function jumpToPxid(txt) {
  if (!state.validator) { statusLabel.setValue('Elegí tu nombre primero.'); return; }
  var t = (txt || '').trim();
  if (t === state.list[state.idx]) return;   // programmatic echo, ignore
  var i = state.list.indexOf(t);
  if (i < 0) { statusLabel.setValue('⚠ ' + t + ' no está en tu lista asignada.'); return; }
  state.idx = i;
  render(true);
}


// =============================================================================
// 6. LAYOUT
// =============================================================================
ui.root.clear();
ui.root.add(controlPanel);
ui.root.add(map);
ui.root.add(chartPanel);
